const ENV = process.env;

const ADMIN_NAME = ENV.ADMIN_NAME;
const ADMIN_PASSWORD = ENV.ADMIN_PASSWORD;

const DEVELOPMENT = ENV.DEVELOPMENT === 'true';

const PLIVO_ID = ENV.PLIVO_ID;
const PLIVO_TOKEN = ENV.PLIVO_TOKEN;
const PLIVO_NUMBER = ENV.PLIVO_NUMBER;

const PORT = ENV.PORT;

module.exports = {
  ADMIN_NAME,
  ADMIN_PASSWORD,
  DEVELOPMENT,
  PLIVO_ID,
  PLIVO_TOKEN,
  PLIVO_NUMBER,
  PORT
};
